repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      name: ruff-check
      args: ['--fix']
    # Run the formatter.
    - id: ruff-format
      name: ruff-auto-format
      args: []

- repo: local
  hooks:
    - id: run-pytest
      name: run-pytest
      entry: bash
      language: system
      types: [python]
      pass_filenames: false
      args:
        - -c
        - |
          echo "Running pytest with PYTHON_ENV=test"
          cd backend && \
          source .venv/bin/activate && \
          PYTHON_ENV=test pytest -s tests  
